language: java

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.9 -qq
  - sudo apt-get upgrade libstdc++6 -qq
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip
  - unzip z3-4.8.10-x64-ubuntu-18.04.zip
  - rm ./z3-4.8.10-x64-ubuntu-18.04.zip
  - export PATH=$PATH:$(pwd)/z3-4.8.10-x64-ubuntu-18.04/bin
  - echo $PATH
  - z3 --version

script: mvn -Pci test
