language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libstdc++6
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip
  - unzip z3-4.8.10-x64-ubuntu-18.04.zip
  - rm ./z3-4.8.10-x64-ubuntu-18.04.zip
  - export PATH=$PATH:$(pwd)/z3-4.8.10-x64-ubuntu-18.04/bin
  - echo $PATH
  - z3 --version

script: mvn -Pci test
