language: java

before_install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-glibc-2.31.zip
  - tar -xvf z3-4.8.12-x64-glibc-2.31.zip
  - rm ./z3-4.8.12-x64-glibc-2.31.zip

script: mvn test -Pci
